#!/bin/bash

echo ==============================================================================
echo Stopping and destroying any existing Vault ...
sudo podman stop vault && sudo podman rm vault
sudo podman volume rm vault-config
sudo podman volume rm vault-data
sudo podman volume rm vault-logs
sudo podman volume rm vault-policies

echo ==============================================================================
echo Starting fresh Vault ...
sudo podman run -d \
  --name vault \
  --restart unless-stopped \
  --cap-add IPC_LOCK \
  -e 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}, "listener": {"tcp": {"address": "0.0.0.0:8888", "tls_disable": 1}}, "ui": 0, "default_lease_ttl": "168h", "max_lease_ttl": "720h", "plugin_directory": "/vault/plugins"}' \
  -e 'VAULT_ADDR=http://0.0.0.0:8888' \
  -e 'VAULT_API_ADDR=http://0.0.0.0:8888' \
  -v vault-config:/vault/config \
  -v vault-policies:/vault/policies \
  -v vault-data:/vault/data \
  -v vault-logs:/vault/logs \
  -p 8888:8888 \
  dcgsteve/vault:002 server
export VAULT_ADDR=http://127.0.0.1:8888

echo ==============================================================================
echo Pause for Vault to come up ...
sleep 2

echo ==============================================================================
echo "Initialising Vault and writing out helper files to user home directory..."
echo "  vault-env    \= environment variables"
echo "  vault-unseal \= unseal script"
echo "  vault-info   \= full key and token info for Vault"
echo "  vault-plugins\= enable use of secrets plugin"
echo ""
echo "Obviously this is only for development not for production \!"
vault operator init > ~/vault-info

echo export VAULT_ADDR=http://127.0.0.1:8888 > ~/vault-env
echo export VAULT_TOKEN=$( cat ~/vault-info | grep 'Initial Root Token' | awk -F ' ' '{print $4}' ) >> ~/vault-env

echo vault operator unseal $( cat ~/vault-info | grep 'Unseal Key 1' | awk -F ' ' '{print $4}' ) > ~/vault-unseal
echo vault operator unseal $( cat ~/vault-info | grep 'Unseal Key 2' | awk -F ' ' '{print $4}' ) >> ~/vault-unseal
echo vault operator unseal $( cat ~/vault-info | grep 'Unseal Key 3' | awk -F ' ' '{print $4}' ) >> ~/vault-unseal

echo vault plugin register -sha256="ddaef75e7b7653e34e8b5efebe6253381a423428b68544cd79149deaff8b5f4e" -command="vault-secrets-gen" secret secrets-gen > ~/vault-plugins
echo sudo podman exec vault setcap cap_ipc_lock=+ep /vault/plugins/vault-secrets-gen >> ~/vault-plugins

chmod u+x ~/vault-unseal
chmod u+x ~/vault-plugins

ls -l ~/vault-*

echo ==============================================================================
echo Done
